#!/bin/sh
nowPath=$(dirname $(readlink -f "$0"))
cp -f $nowPath/my.cnf /etc/mysql/my.cnf
mysql_install_db --user=mysql --ldata=/var/lib/mysql
rc-service mysqld start
#mysqladmin -u root password 'guning666'
